# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QLabel, QLineEdit,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStackedWidget, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(982, 666)
        MainWindow.setMinimumSize(QSize(350, 220))
        font = QFont()
        font.setPointSize(15)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(66, 218, 255, 255), stop:0.482955 rgba(216, 154, 255, 255), stop:1 rgba(255, 255, 153, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(129, 218, 255, 255), stop:0.482955 rgba(216, 180, 255, 255), stop:1 rgba(255, 255, 188, 255));")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(40, 20, 921, 521))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.page.setStyleSheet(u"background-color: rgb(255, 170, 255);\n"
"background-color: rgb(253, 224, 255);")
        self.label_image = QLabel(self.page)
        self.label_image.setObjectName(u"label_image")
        self.label_image.setGeometry(QRect(30, 70, 400, 251))
        self.label_image.setMinimumSize(QSize(400, 220))
        self.label_image.setStyleSheet(u"background-color: rgb(248, 255, 247);")
        self.label_image.setScaledContents(True)
        self.label_image_detect = QLabel(self.page)
        self.label_image_detect.setObjectName(u"label_image_detect")
        self.label_image_detect.setGeometry(QRect(480, 70, 391, 251))
        self.label_image_detect.setMinimumSize(QSize(375, 220))
        self.label_image_detect.setStyleSheet(u"background-color: rgb(248, 255, 247);")
        self.label_image_detect.setScaledContents(True)
        self.pushButton_image = QPushButton(self.page)
        self.pushButton_image.setObjectName(u"pushButton_image")
        self.pushButton_image.setGeometry(QRect(340, 420, 211, 31))
        self.pushButton_image.setStyleSheet(u"font: 700 9pt \"Microsoft YaHei UI\";")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setStyleSheet(u"background-color: rgb(243, 250, 255);")
        self.pushButton_open = QPushButton(self.page_2)
        self.pushButton_open.setObjectName(u"pushButton_open")
        self.pushButton_open.setGeometry(QRect(50, 400, 101, 24))
        font1 = QFont()
        font1.setFamilies([u"Microsoft YaHei UI"])
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setItalic(False)
        self.pushButton_open.setFont(font1)
        self.pushButton_open.setStyleSheet(u"font: 700 10pt \"Microsoft YaHei UI\";")
        self.pushButton_close = QPushButton(self.page_2)
        self.pushButton_close.setObjectName(u"pushButton_close")
        self.pushButton_close.setGeometry(QRect(50, 450, 101, 24))
        self.pushButton_close.setFont(font1)
        self.pushButton_close.setStyleSheet(u"font: 700 10pt \"Microsoft YaHei UI\";")
        self.label_cap = QLabel(self.page_2)
        self.label_cap.setObjectName(u"label_cap")
        self.label_cap.setGeometry(QRect(30, 70, 400, 251))
        self.label_cap.setMinimumSize(QSize(400, 220))
        self.label_cap.setStyleSheet(u"background-color: rgb(248, 255, 247);")
        self.label_cap.setScaledContents(True)
        self.label_cap_detect = QLabel(self.page_2)
        self.label_cap_detect.setObjectName(u"label_cap_detect")
        self.label_cap_detect.setGeometry(QRect(490, 70, 400, 251))
        self.label_cap_detect.setMinimumSize(QSize(400, 220))
        self.label_cap_detect.setStyleSheet(u"background-color: rgb(248, 255, 247);")
        self.label_cap_detect.setScaledContents(True)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setStyleSheet(u"background-color: rgb(252, 255, 222);")
        self.label_video = QLabel(self.page_3)
        self.label_video.setObjectName(u"label_video")
        self.label_video.setGeometry(QRect(20, 60, 400, 251))
        self.label_video.setMinimumSize(QSize(400, 220))
        self.label_video.setStyleSheet(u"background-color: rgb(248, 255, 247);")
        self.label_video.setScaledContents(True)
        self.label_video_detect = QLabel(self.page_3)
        self.label_video_detect.setObjectName(u"label_video_detect")
        self.label_video_detect.setGeometry(QRect(510, 60, 391, 251))
        self.label_video_detect.setMinimumSize(QSize(375, 220))
        self.label_video_detect.setStyleSheet(u"background-color: rgb(248, 255, 247);")
        self.label_video_detect.setScaledContents(True)
        self.pushButton_video = QPushButton(self.page_3)
        self.pushButton_video.setObjectName(u"pushButton_video")
        self.pushButton_video.setGeometry(QRect(360, 390, 211, 31))
        self.pushButton_video.setStyleSheet(u"font: 700 9pt \"Microsoft YaHei UI\";")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.page_4.setStyleSheet(u"background-color: rgb(254, 248, 255);")
        self.lineEdit_url = QLineEdit(self.page_4)
        self.lineEdit_url.setObjectName(u"lineEdit_url")
        self.lineEdit_url.setGeometry(QRect(260, 120, 421, 20))
        self.lineEdit_url.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label = QLabel(self.page_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(180, 120, 54, 16))
        font2 = QFont()
        font2.setBold(True)
        font2.setItalic(True)
        self.label.setFont(font2)
        self.label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pushButton_get_video = QPushButton(self.page_4)
        self.pushButton_get_video.setObjectName(u"pushButton_get_video")
        self.pushButton_get_video.setGeometry(QRect(380, 193, 141, 31))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(True)
        self.pushButton_get_video.setFont(font3)
        self.stackedWidget.addWidget(self.page_4)
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(30, 570, 191, 22))
        font4 = QFont()
        font4.setPointSize(9)
        font4.setItalic(True)
        self.comboBox.setFont(font4)
        self.pushButton_model = QPushButton(self.centralwidget)
        self.pushButton_model.setObjectName(u"pushButton_model")
        self.pushButton_model.setGeometry(QRect(740, 570, 151, 24))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(True)
        self.pushButton_model.setFont(font5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 982, 32))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_image.setText("")
        self.label_image_detect.setText("")
        self.pushButton_image.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u68c0\u6d4b", None))
        self.pushButton_open.setText(QCoreApplication.translate("MainWindow", u"\u5f00\u542f\u6444\u50cf\u5934", None))
        self.pushButton_close.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u6444\u50cf\u5934", None))
        self.label_cap.setText("")
        self.label_cap_detect.setText("")
        self.label_video.setText("")
        self.label_video_detect.setText("")
        self.pushButton_video.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u68c0\u6d4b", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u7f51\u5740", None))
        self.pushButton_get_video.setText(QCoreApplication.translate("MainWindow", u"\u89c6\u9891\u83b7\u53d6", None))
        self.pushButton_model.setText(QCoreApplication.translate("MainWindow", u"\u6a21\u578b\u9009\u62e9", None))
    # retranslateUi

